### ISSUE TITLE
Error: "DataFrame" object has no attribute 'ix'

### ISSUE THREAD

**Issue by jannisanstatt** [cmbi/copal#1]
Hello,

I wanted to use CoPAL via the GUI, however, when I start it the following error message appears: " 'DataFrame' object has no attribute 'ix'". I think the reason is that the '.ix' command was removed in a new Pandas version but, surprisingly, even loading the required older pandas version (0.23.4) did not solve the problem. Do you know whether this has occurred before and how I could fix this?

Thanks a lot!

Best
Jannis

**Comment by joerivstrien** [comment]
Hi Jannis,

Thank you for pointing this out, that is indeed curious. I will have a look at this asap, and get back to you.

Best,

Joeri

**Comment by joerivstrien** [comment]
Some questions: 

Could you verify whether you are running the GUI from python or if you are running the prepackaged executable?

If running it from python, could you or did you check that the python you are running is indeed using the older version of the pandas package (by checking the version from within python, using something like this: "print(pd. \__version\__)" )?

Thanks!

Joeri

**Comment by jannisanstatt** [comment]
Hi Joeri,

Thanks for your answer!

While checking the pandas version I found the solution for the problem: Instead of running "python copal\COPAL_gui.py" I just ran "copal\COPAL_gui.py" which also opened the gui but apparently did not make use of the correct python version. Thanks again for your help and sorry that I didn't realize this earlier!

Best
Jannis

**Comment by joerivstrien** [comment]
Hi Jannis,

Great! Good to hear that it's working now.

Best,

Joeri
